### ISSUE TITLE
About me/Profile pics

### ISSUE THREAD

**Issue by sapphicwench** [nataliecursio/XVI#13]

**Comment by sapphicwench** [comment]
Just copy everything from A1?

**Comment by NessLouise** [comment]
Yeh pretty much! I've taken mine and added a couple of bits so it reflects the requirements (detailed below)! 

_**Personal information**
One paragraph per person, including name, student number, background, hobbies, IT interest and IT experience. This should also include your team’s chosen name._

**Comment by sapphicwench** [comment]
@NessLouise Complete
@nataliecursio Compltete f2d9abfc6bb13ed46e36b9c67baaa1ae5f723acb
@CptVeg complete 2c53e02dec0c352b7bb270f8c339d77170660c41
@CorbinCoder complete
awaiting Oliver

**Comment by NessLouise** [comment]
@ollie3203 complete
