### ISSUE TITLE
Group Reflection

### ISSUE THREAD

**Issue by sapphicwench** [nataliecursio/XVI#14]
Towards the end of the assignment period, you should reflect as a group on how well
you think you have performed in this assignment. You should include whatever
evidence you may have about the groups processes (such as commit trails from
GitHub, or project meeting minutes). Each member of the group should contribute up
to 200 words about their own perception of the group, and the group as a whole
should contribute around 400 words. This should include the following attributes.
• What went well
• What could be improved
• At least one thing that was surprising
• At least one thing that you have learned about groups
• Remember to include in your section on Tools how well you think your Github log of
activity reflects your group’s work on this assignment.

**Comment by sapphicwench** [comment]
@CorbinCoder complete 61a770a94425d27708b374a1abb30cb4a76d102b

**Comment by sapphicwench** [comment]
@CptVeg complete 0e5d13d15ded56645576266537d25eda31cd5e59

**Comment by nataliecursio** [comment]
@nataliecursio done my para

**Comment by sapphicwench** [comment]
smashed out on discord!

**Comment by sapphicwench** [comment]
compreto per c18ad6dd247ea8f0570b519f93826312c19a1e81
