### ISSUE TITLE
Project Idea - Choosing on and reporting

### ISSUE THREAD

**Issue by sapphicwench** [nataliecursio/XVI#8]

**Comment by sapphicwench** [comment]
Project idea has been voted on - Eldery Engagment Chat - (SocialCare Chat? Do we need to think of a better name?)

**Comment by sapphicwench** [comment]
@CorbinCoder is taking the technology side of repot
@CptVeg Expanding on project idea

**Comment by NessLouise** [comment]
Oh I love that @CptVeg

**Comment by sapphicwench** [comment]
per 314f2d5322ff2ac3b2e96b1e4f6af4b9ac427566 draft has been pushed

**Comment by sapphicwench** [comment]
Approx. 250 words each

Website > mobile application html-y

@NessLouise: Scope: we are looking have certain functionalities

@CorbinCoder: Methods: technologies 

@ollie3203 : Plan for testing: Beta testing, afterwards fully-fledged application

@CptVeg: Launch/marketing: How do we get it into their hands 

@nataliecursio  Roles:  tie back to ideal jobs/Photos/images/marketing types

@NessLouise : Conclusion:

**Comment by sapphicwench** [comment]
@CorbinCoder: Methods: technologies - COMPLETE 9903c2fee625747445b266fe82c67b16534314bd

**Comment by sapphicwench** [comment]
@CptVeg  Launch/marketing: How do we get it into their hands - COMPRETO b8c68fcf20ef8410cf9902532de4d9ac6428558a

**Comment by sapphicwench** [comment]
@nataliecursio section complete per 1ed42a5825e9c919745e84bc06894234e12c6c9f and 8e6429fff34994708a345fe88f48ec0518432974
@NessLouise complete per 64a1a3f5340cd893e915675f22a3ff313ffd10a1
@ollie3203 complete per b8cb0e249e6c2fcaea3b30e006011f38328ad632
